name: Lint, Test, Make local PR, Make PR to the Repo

on:
  push:
    branches-ignore:
      - main

jobs:
  lint-test-make-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy files
        run: |
          mkdir workadventure
          cp -r templates workadventure
          cp {.helmignore,Chart.yaml,LICENSE,README.md,values.yaml} workadventure

      - name: set up helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: helm-check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: .

      - name: pull-request-local
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pulling ${GITHUB_REF##*/} into main"
          pr_template: ".github/pull_request_template.md"
          pr_reviewer: "wei,worker"
          pr_label: "auto-pr"

      - name: pull-request-repo
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'workadventure'
          destination_repo: 'iits-consulting/helm-charts'
          destination_folder: 'charts'
          destination_base_branch: "${GITHUB_REF##*/}"
          destination_head_branch: "${GITHUB_REF##*/}"
          user_email: 'denis.lavrushko@iits-consulting.de'
          user_name: 'denis.lavrushko'
          pull_request_reviewers: 'reviewers'

############ leave this for main chart repo #############
#      - uses: actions/setup-python@v2
#        with:
#          python-version: 3.7
#
#      - name: Set up chart-txesting
#        uses: helm/chart-testing-action@v2.0.1
#
#      - name: Run chart-testing (list-changed)
#        id: list-changed
#        run: |
#          changed=$(ct list-changed)
#          if [[ -n "$changed" ]]; then
#            echo "::set-output name=changed::true"
#          fi
#
#
#      - name: Run chart-testing (lint)
#        run: ct lint
#
#      - name: Create kind cluster
#        uses: helm/kind-action@v1.0.0
#        if: steps.list-changed.outputs.changed == 'true'
#
#      - name: Run chart-testing (install)
#        run: ct install
