name: Merge to the main

on:
  push:
    branches:
      - main

jobs:
  release-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get PR info
        id: pr_info
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "${{ steps.pr_info.outputs.labels }}"

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump_semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.pr_info.outputs.labels }}

      - run: echo "${{ steps.bump_semver.outputs.new_version }}"

#      - id: bump
#        uses: zwaldowski/match-label-action@v1
#        with:
#          allowed: major,minor,patch
#
#      - uses: zwaldowski/semver-release-action@v1
#        id: next_version
#        with:
#          dry_run: true
#          bump: ${{ steps.bump.outputs.match }}
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#      - run: echo "${{ steps.next_version.outputs.version }}"